name: "Generate Amazing Podcasts"
author: "Hassaan Shariq"
description: "Podcast Generator for YAML File"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committers email
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The committers name
    required: true
    default: ${{github.actor}}
